GrafeasGroup/blossom

authentication/mixins.py
blossom/templates/website/generic_form.html
blossom/templates/website/partials/base.partial
website/helpers.py
website/views.py

Closes #116 
I went in to fix the width issue on staff pages, but discovered a minor problem in that any user logged into the application (currently not possible, but will be once we begin work on the actual transcription app) could edit things on the homepage. I went ahead and added an extra permissions class to handle that.
Also removes a few dead views.

Front-end fixes & permissions updates

---

api/views/submission.py

Relevant issue: {issue url}
{description}
{if applicable}
{testing instructions}

Add logging to done request

---

api/tests/submissions/test_submission_creation.py
api/tests/submissions/test_submission_done.py
api/views/submission.py

Relevant issue: {issue url}
{description}
{if applicable}
{testing instructions}

Change retrieval of booleans

---

api/tests/submissions/test_submission_done.py
api/tests/test_volunteers.py
api/views/submission.py
api/views/transcription.py
authentication/models.py
blossom/settings/base.py

Relevant issue: {issue url}
{description}
{if applicable}
{testing instructions}

Fix gamma calculation and boolean from string

---

api/views/submission.py

Closes #138 
@TimJentzsch identified an overly complex query and the fix -- this is just committing that fix.

Simplify transcribot query

---

api/views/misc.py

Closes #180 
The Summary generator still uses the original method we had for counting transcriptions before transcribot generated its own objects. This PR adjusts the behavior of the summary to get an accurate count.

fix total transcription count

---

api/tests/submissions/test_submission_done.py
authentication/models.py

Adds Pink (25 gamma) and Sapphire (20,000 gamma) as ranks.

Add Pink and Sapphire ranks

---

api/views/slack_helpers.py
bootstrap/helpers.py

Copy/pasting a username sometimes makes it a link, which we can't process appropriately. Add logging so we can see exactly what we're working with. Will be removed when appropriate logic is added.

add logging to identify exactly what slack is sending

---

api/tests/submissions/test_submission_get.py
api/tests/test_transcriptions.py
api/views/submission.py
api/views/transcription.py
poetry.lock
pyproject.toml

Relevant issue: Closes #212.
This adds the `text__icontains` query parameter to the transcription endpoint as well as the `title__icontains` query parameter to the submission endpoint. This enables clients (like Buttercup)  to implement a search function.
Originally I intended to add the case-sensitive versions as well, but for some reason they were also case-insensitive.

Add query parameters to search in transcription text and submission title

---

api/serializers.py

Turns out everything else we need for title / nsfw is already there, so all we should have to do is this little change to add nsfw to the serializer. :tada:

add nsfw to serializer

---

api/admin.py
app/permissions.py
app/reddit_actions.py
app/urls.py
app/views.py
blossom/settings/base.py
blossom/templates/app/partials/errors/no_transcriptions.partial
blossom/templates/app/view_transcriptions.html
blossom/templates/website/partials/navbar.partial
blossom/urls.py

Adds edit functionality to the app.
(note: green button now says "View Comment")

App edit functionality

---

app/views.py

If a space is put at the end of the content type, Reddit won't render the formatting correctly.

Fix header rendering

---

README.md
api/views/proxy.py
api/views/slack_helpers.py
app/middleware.py
app/permissions.py
app/reddit_actions.py
app/tests/test_views.py
app/views.py
blossom/errors.py
blossom/management/commands/generate_dev_data.py
blossom/urls.py
utils/workers.py

Working on Blossom has gotten massively more complicated, and that's pretty much entirely my fault. This PR walks back some of the complexity or provides early escapes for logic based on whether the server is in debug mode and a combination of flags that can be found in `local_settings.py`. If you are setting up the server with dummy data, please follow the new directions to make sure that everything works the way that it should.

Rework app to function cleanly for local development

---

api/tests/submissions/test_submission_done.py
api/views/slack_helpers.py
api/views/submission.py
app/views.py
blossom/settings/base.py
utils/workers.py

Does the same thing as #310, just in a slightly less invasive way.

update slack pings to go to new channels

---

bootstrap/__init__.py
bootstrap/migrate_redis_data.py
bootstrap/multi-comment-transcriptions.py
bootstrap/sync_removal.py

Multi comment transcriptions weren't picked up properly by bot, only the first comment made it to Blossom.
This script goes through the transcriptions and fixes them in the database.
:information_source:  This PR is branched from #349, so that should be merged first. :information_source:

Add script to fix multi comment transcriptions

---

api/models.py
api/slack/actions.py
api/tests/submissions/test_submission_approve.py
api/tests/submissions/test_submission_remove.py
api/views/submission.py

When a submission gets removed or approved via the API endpoints, the Slack report message is now updated accordingly.

Update Slack report messages with API

---

api/tests/submissions/test_submission_done.py
api/views/submission.py

Relevant issue: Closes #377
QA requested that checks are generated even if the transcription has been marked as removed.

Create a transcription check even if it was removed on Reddit

---

api/slack/transcription_check/blocks.py
api/slack/utils.py
api/tests/slack/test_utils.py

Relevant issue: Closes #376, closes #382
This PR adds the subreddit to the transcription check messages, as well as displaying an indicator and hiding the preview image if the submission is marked as NSFW.

Add NSFW indicator and subreddit to check messages

---

.github/workflows/bump-version.yml
pyproject.toml

Re-opening this PR to verify that the everything works properly, but the gist is that it now updates the patch version once per PR instead of once per push to master.

Move bump-version to PR only

---

api/slack/commands/__init__.py
api/slack/commands/checkstats.py
api/slack/commands/info.py
api/slack/commands/utils.py
api/tests/slack/commands/test_checkstats.py
pyproject.toml

Relevant issue: Closes #408
This command shows stats about the checks that the given mod has processed.

Add Slack checkstats command

---

authentication/models.py
authentication/tests/test_blossomuser.py

Update to models.py and test_blossomuser.py for new low activity threshold (5->10).

Low Activity Threshold Update

---

blossom/api/slack/commands/__init__.py

Forgot to change the actual name of the command.

change command name

---

blossom/settings/base.py
pyproject.toml

Staticfiles aren't getting properly added into the archive. This fixes that.

update staticfiles globs

---

blossom/authentication/models.py

Adds Garnet as 30,000+ rank color.

Add Garnet rank color

---

blossom/api/models.py
blossom/api/tests/submissions/test_submission_subreddits.py
blossom/api/views/submission.py

Relevant issue: Closes #470
Adds a new endpoint to count submissions by subreddit.
All filters that are usable for submissions can be applied.

Add `submission/subreddits` endpoint
