api/tests/submissions/test_submission_done.py
api/tests/submissions/test_submission_yeet.py
api/views/submission.py

While verifying the dummy transcriptions created by the bootstrap script, it looks like there are a handful of users who have _more_ dummy transcriptions than they should. This adds an endpoint that I can use to clean up dummy transcriptions with appropriate tests.
Also fixes single piece of feedback from #115 with appropriate test fix.

Add additional endpoint for handling extra submissions

---

blossom/static_dev/css/main.css
blossom/templates/website/index.html

Rather than dealing with manually remembering to mark links as underlined, this adds a CSS tweak so that it happens automatically.

automatically underline links made in the body of blog posts

---

blossom/static_dev/css/main.css
blossom/templates/website/index.html
blossom/templates/website/post_detail.html

Adds automatic underlining of links to the post detail page.

Underline links on detail page

---

.github/workflows/static-analysis.yml
.github/workflows/tests.yml
blossom/instrumentation.py
blossom/settings/base.py
poetry.lock
pyproject.toml

Application tracing using Honeycomb. See docs on integrating `beeline`, their library for handling this tracing and automatically instrumenting frameworks like Django, Tornado, Flask, etc.
The only way this would be visible is to add it to the `gunicorn` invocation via:
`gunicorn -c /path/to/blossom/instrumentation.py ...`
and giving an environment variable `HONEYCOMB_KEY` with a non-empty string value. Otherwise it logs calls to stderr and should have zero impact on how the application runs.

Application tracing with Honeycomb

---

blossom/__init__.py
blossom/settings/base.py

By reading from the `pyproject.toml`, we can tell the version string. Even if it doesn't exist, it fails gracefully with a version string of `unknown`.
Given our deployment strategy preserves `pyproject.toml` next to the source code, this should be an okay assumption to make.

Tell Bugsnag what version of Blossom is running

---

.flake8
README.md
blossom/settings/base.py
docker-compose.yml
docker/blossom-entrypoint.sh
docker/blossom.Dockerfile
docker/init.sql
docker/local_settings.py
docker/nginx.conf

For closer emulation to what is running on prod, here's a `docker-compose` manifest and associated files for running blossom entirely locally using Docker and `docker-compose` as an orchestrator.

Emulates blossom deployment with docker-compose

---

blossom/templates/website/admin.html
blossom/templates/website/index.html
blossom/templates/website/post_detail.html

Adds the date to posts that aren't in the menu bar (like the donation page / about page) and also trades out the boolean field in the admin panel for ✓ / ✗ instead of True / False.
Post detail view:
Index view:
Note that header bar posts are unaffected:
Admin panel change:

show date on most posts and clean up display of admin panel

---

api/urls.py

Relevant issue: Closes #131
This adds a custom OpenAPISchemaGenerator in order to add `/api/` to all API requests on Swagger.

Add custom OpenAPISchemaGenerator to fix Swagger endpoint URLs

---

api/serializers.py

Makes the API return `content_url` along with the other fields.

add content_url to the serialized fields

---

blossom/templates/website/partials/base.partial

This adds Plausible support for the website. Plausible is an ethical metrics company that I've used for my own sites for a year and I have an extra slot to add in for Grafeas, so why not? Here's the dashboard for my filament website -- the metrics collected are exactly the same and we can make the dashboard public for all to see. https://plausible.io/filamentcolors.xyz

Add Plausible

---

website/models.py
website/urls.py
website/views.py

When I set up the routes for the posts on the website, I used pk+slug (`1-our-story`) so that we could have multiple posts with the same name and still tell them apart. That's a great idea as long as the primary key doesn't change, and for some reason it is and the PK of our donations page keeps changing and invalidating its own URL. This PR:
* swaps over to slug only routes
* provides a compatibility redirect layer for the routes we've already publicized -- can be removed after we forget why we added it

Change url routes to remove pk

---

blossom/templates/website/partials/base.partial
blossom/templates/website/post_detail.html

Relevant issue: #151 
Adds card support for Twitter and Facebook. Uses the formatting developed for https://filamentcolors.xyz, which will translate nicely to what we need. This PR handles updating the title and body of the card depending on whether we're looking at a main page or a post detail.

Adds facebook and twitter cards to pages

---

api/pagination.py
blossom/settings/base.py

Relevant issue: Closes #156.
This changes the default pagination class to a custom one. This allows us to set a `page_size` parameter to control the number of items per page. The current maximum is set to 500, but we might wanna adjust this to our needs.
This change is important for buttercup to reduce the number of API requests and thus the delays.

Add custom default pagination class

---

api/views/misc.py
api/views/submission.py
api/views/transcription.py
api/views/volunteer.py

Currently the bots call out to a non-existent API endpoint to harvest a CSRF token, then call to the appropriate API. That results in lots of errors generated. I'm arguing here that it isn't necessary to protect the API like that.
Given CSRF protection is an anti-bot measure, an API by nature is intended for bots, and we are already authenticating every request with an API token, applying exemptions to all authenticated API endpoints seems prudent.

[RFC] Exempt the API from CSRF protections

---

api/tests/submissions/test_submission_transcribot_queue.py
api/views/submission.py

Matching tor_ocr PR: https://github.com/GrafeasGroup/tor_ocr/pull/40
The single most time-intensive database query right now belongs to the transcribot queue query, taking roughly half a second to process and called every two seconds. This PR does two things:
* drastically limits the data that is actually pulled from the database
* bypasses the serializer, which chops off a fair amount of extra processing we don't need
We will not know _how much_ of a difference this makes until this is deployed and we can observe with honeycomb, but my gut reaction is that we should see a significant change.

Slim down logic for transcribot queue

---

blossom/templates/website/generic_form.html

This removes the JQuery used in the form validation code in #159. The functionality should be identical, to the best of my knowledge.
I also removed a potential attack vector for script injection and handling in case that the forms don't have the expected structure.
If we are to proceed with this, first move this PR and then #159.

Remove JQuery from form validation code

---

api/tests/test_volunteers.py
api/views/volunteer.py

Relevant issue: GrafeasGroup/buttercup#29, Closes #166
Adds a `/volunteer/heatmap` endpoint to get the data necessary to create a heatmap like this:
It counts how many transcriptions a user has done in each hour of each day of the week.
For the response, unfortunately Sunday is 1 and Saturday 7, blame Django for that.

Add `/volunteer/heatmap` endpoint

---

authentication/views.py
blossom/management/commands/bootstrap_site.py
blossom/settings/base.py
blossom/static_dev/js/potentially.js
blossom/templates/website/admin.html
blossom/templates/website/error.html
blossom/templates/website/generic_form.html
blossom/templates/website/partials/base.partial
blossom/templates/website/partials/navbar.partial
blossom/templates/website/post_detail.html
blossom/urls.py
website/forms.py
website/templatetags/string_helpers.py
website/urls.py
website/views.py

Relevant issue: #145 
Since we started working on this so long ago, it still uses bootstrap4 -- it's better to change over sooner rather than later so that we have fewer things to break. This PR:
* removes bootstrap4
* expands the generic form
* adds error handling views for 404 and 500
* fixes Plausible.js metrics loading
* fixes navbar support for engineering blog
* fixes navbar support for mobile
Turns out that adblock lists are literally just looking for a script called `plausible.js`, no matter where it's loaded from -- so on the recommendation of Plausible, we'll now self-host the script and I've changed the name to `potentially.js`, which, hilariously, is enough to make it load. I've also disabled it if you're logged into the site, since we don't really want to track page views on …

Convert site from Bootstrap4 to Bootstrap5

---

.isort.cfg
api/filters.py
api/tests/submissions/test_submission_get.py
api/views/submission.py
poetry.lock
pyproject.toml

Allow using query string parameters to filter submission objects. Examples:
```
/api/submission/?from=2021-06-03
/api/submission/?from=2021-06-01&until=2021-07-01
/api/submission?from=yesterday
/api/submission?from=march+7th+at+8pm&until=april+12th+at+2pm
```
Needed for buttercup and data science integrations.

Add time-based filtering for Submissions

---

api/views/volunteer.py

I forgot to add the "none" option to the `time_frame` parameter of the `volunteer/rate` endpoint, because I'm stupid.
This change makes it show up properly in Swagger.

Fix enum of time_frame parameter for rate endpoint

---

api/tests/submissions/test_submission_get.py
api/tests/test_transcriptions.py
api/views/submission.py
api/views/transcription.py

Relevant issue: Closes #172 
This uses the `OrderingFilter` general filter back-end to provide an `ordering` query parameter. This can be used to explicitly control the ordering of the API results.
For example, `/api/submission/?ordering=complete_time` and `api/submission/?ordering=-complete_time` will return the submissions filtered by the time they were completed at, ascending and descending respectively.
I added orderings to the `submission`, `transcription` and `volunteer` endpoints.

Add query parameter to order API results explicitly

---

blossom/instrumentation.py

Right now we are sending an insane number of events to Honeycomb -- we need to drastically cut that down in order to fit in our usage tier. Per the documentation suggestion of Beeline (Honeycomb.io's python library that we use) I've set a sampling rate of 10 and we can adjust from there if we don't like it.

Update honeycomb init to include sample rate

---

api/tests/submissions/test_submission_claim.py
api/views/submission.py

Relevant issue: Closes #182
This enforces a limit on the maximum number of submissions a user can claim at the same time.
When the limit is reached, claiming returns status code `460`  and a list of the claimed submissions. This can then be used by u/tor to warn the user.

Prevent mass claiming of submissions

---

api/tests/submissions/test_submission_claim.py
api/views/submission.py

Relevant issue: GrafeasGroup/tor#187, Closes #184
When a submission is claimed and then tried to claim again, the user who already claimed the submission is returned along with the error code. u/tor can use this to determine if it was the same person or another person and adjust the message accordingly.

Return user who already claimed a submission

---

api/serializers.py

Adds the `title` attribute to the Submission serializer. This makes it actually visible in the API and also (maybe?) available to the `PATCH` call.

Add title attribute to submission serializer

---

api/tests/test_misc.py
api/views/misc.py

Relevant issue: Closes #198.
This counts the number of volunteers who completed a submission in the last two weeks. This gives us a sense of how many volunteers are actually still transcribing.

Add active_volunteer_count to summary endpoint

---

api/filters.py
api/tests/submissions/test_submission_get.py

Relevant issue: Closes #202.
There was a bug in the implementation of the `TimeFilter` backend that resulted in errors when providing timezone aware time strings as `from` or `until` parameters.
Specifically, it always used `timezone.make_aware` on the parsed time, which fails when the given time is already timezone aware.
Instead, the default timezone is now provided directly to the date parser.

Fix TimeFilter backend for timezone aware times

---

api/tests/submissions/test_submission_get.py
api/tests/test_transcriptions.py
api/views/submission.py
api/views/transcription.py

Relevant issue: Closes #201
This PR adds `isnull` filters to the endpoints, allowing clients to exclude or include `null` entries in the listings. This allows several new queries, such as getting all posts in the queue and getting all in-progress posts by a user.
For example, the submission endpoint now allows query parameters like `?completed_by__isnull=true` which gets all submissions that have not been completed yet.

Add `isnull` filters to endpoints

---

.flake8
api/tests/test_slack.py
api/views/slack_helpers.py
bootstrap/helpers.py

Enable processing of copy / pasted usernames with fancy links in slack.
Example, existing implementation:
```
@blossom reset itsthejoker  # would work
@blossom reset <https://reddit.com/example|itsthejoker>  # slack can automatically carry that formatting if copied and pasted, and this would not work
```
With this PR, both of those commands will function as expected. Also ported for the `blacklist` command.

Allow processing slack username pings with links in them

---

.flake8
.gitignore
README.md
blossom/settings/routing.py

Moves the need for the local_settings.py file from inside the `blossom` folder to at the top level. When any command using manage.py is run, the file will be automatically loaded and run if it's detected.
**BREAKING CHANGE**: Must move `local_settings.py` from inside the `blossom` folder to the top level!

Remove need for settings flag on all commands locally

---

api/tests/test_transcriptions.py
api/views/transcription.py

Relevant issue: Closes #221, required by GrafeasGroup/buttercup#106.
This adds `create_time__gt`/`create_time__gte`/`create_time__lte`/`create_time__lt` query parameters to the transcription endpoints to filter the transcriptions by time.
In the future, I plan to also replace the submission time filter by this system. This would allow the client to filter by `create_time`, `claim_time` and `complete_time` separately. However, that would be a breaking change so I'll do it in another PR.

Add transcription time filters

---

api/tests/test_slack.py
api/views/slack.py
api/views/slack_helpers.py
blossom/settings/base.py

Need to actually verify that requests coming in on the slack endpoint actually come from slack. This is a security hole and also since I'm about to implement a command that modifies data, we need to be extra sure. The actual process for verifying is a pain in the butt, but I think that this is accurate.

add slack verification

---

api/urls.py
api/views/find.py

Relevant issue: Closes #225.
In #223 I added the `/find/` endpoints to get submissions/transcriptions by their URL, but I forgot to actually enable it for usage.
This PR fixes this problem, so that we can actually use it.
It also improves/fixes the Swagger documentation for the endpoint.

Enable `/find/` endpoint

---

api/views/find.py

While the `/find/` endpoint was finally visible, it always returned an error response.
Turns out that the `url` query parameter wasn't extracted properly so the value was always `None`.
I more or less tested it on the local setup so it should actually work now (hopefully).
Additionally, this fixes some types and makes the `url` parameter required.

Fix url parameter of find endpoint not being extracted properly

---

api/serializers.py
api/views/find.py

This is another PR on the long road of fixing the `/find/` endpoint.
Here, we are adding a custom serializer for the response, so that we don't get type errors.
I could confirm on my local instance that the submission is now returned properly and that no error occurs.
Whether the author and transcription are also returned correctly is hard to test locally without creating and patching a bunch of objects. So I'm hoping that this will be the last PR.

Add custom serializer for the response of the find endpoint

---

.isort.cfg
blossom/settings/base.py
blossom/templates/website/generic_form.html
blossom/templates/website/index.html
blossom/urls.py
poetry.lock
pyproject.toml
website/urls.py

So we have a minor problem. The transcription app is designed to be accessed from thetranscription.app and the rest of the site is designed to be accessed from grafeas.org... and they shouldn't share resources. We don't want thetranscription.app/payments to respond to things, after all. This PR adds in a simple redirect system so that if you try to come into a route that is meant for the other domain, the server issues you a 302 so that you can load it from the proper domain name. I can't properly test this without deploying it, but it seems to work; I also fixed the DNS issues so now thetranscription.app actually resolves.
The other major issue is that in order to authenticate with Reddit, we need to give it one URL -- so we basically have to force login to only …

Fix Domain Names

---

api/tests/test_find.py
api/views/find.py

Relevant issue: Closes #234
The `/find/` endpoint will now truncate the given URL to the minimal part that still contains the ID of the submission.
It then tries to find the submission with a `startswith` filter.
This greatly simplifies the logic, because we don't have to handle transcriptions separately anymore.
Additionally we can handle more types of URLs, for example `claim`/`done` comments can be found now.
Transcriptions not being found has also been fixed.
The only downside is that it might be slower, because we cannot use simple equality checks anymore.
Personally, I think this is worth it.

Simplify logic to find posts in `/find/` endpoint

---

.github/workflows/bump-version.yml
pyproject.toml

It bothers me that we keep redeploying 0.4.0, so this PR adds a new action that (hopefully) will increment the minor version number every time we push to master (merge a PR). There's no way to detect merging a PR specifically, but this should be good enough. I also set the version number to 1.0.0 because Blossom has been stable for a while and that's worth celebrating :tada: 
References:
- https://github.com/marketplace/actions/add-commit
- https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359
- https://python-poetry.org/docs/cli/

add what hopefully is a working actions workflow

---

api/serializers.py
api/tests/test_find.py
api/views/find.py

Relevant issue: Closes #235 
The `/find/` endpoint will now also create the OCR transcription if one is available for the given post.

Add OCR to `/find/` response

---

app/reddit_actions.py
blossom/templates/app/transcribing.html

Relevant issue: #275 
All transcription text is automatically escaped for security reasons, but because it's being dropped right into SimpleMDE then we can mark it as safe and let normal HTML characters (`< > & %` to name a few) render as expected.

Mark transcription text as safe

---

blossom/templates/app/transcribing.html

Relevant issue: #248
Converts the initial text from actual content in the text field to the SimpleMDE-specific placeholder text.

Fix placeholder text for editor

---

api/tests/test_find.py
api/views/find.py

Relevant issue: Closes #280
The `author` field of the `/find/` response for in-progress posts was `null`, instead of showing the user that claimed the post.
This is because it used the `completed_by` field instead of the `claimed_by` field.

Fix `author` being `null` for in-progress posts of `/find/` response

---

blossom/templates/app/transcribing.html

Relevant issue: #279 
The markdown editor for the transcription app didn't clear properly when starting a new transcription.
Instead, it included the text of the previous transcription.
This PR sets the default content to be empty, hopefully resolving this issue.
⚠️ I haven't tested this at all, so I have no idea if it actually works ⚠️

Fix markdown editor not clearing content for new transcription

---

blossom/templates/app/choose_transcription.html

Relevant issue: Closes #255
This PR restructures the transcription choice page:
- Moves the list of in-progress transcriptions to the very top for better visibility
- Moves the "Reroll!" button to the top so that it stays at the same place after refreshing
- Removes some verbose text to save space

Add additional reroll button and in-progress transcriptions to top of page

---

app/views.py
blossom/templates/app/transcribing.html

Relevant issue: Closes #274
This hides the "Reroll" button when editing a transcription.

Hide reroll button in edit mode

---

app/urls.py
app/views.py
blossom/templates/app/partials/transcription_card.partial

Relevant issue: Close #259
This adds a second button to the transcription cards which allows the users to report a post without claiming it first.
Go to https://thetranscription.app/app/ and you should see a "Report" button for each transcription card.
When you click the button, it should show a modal to choose the report reason.
When you click the report reason it should send the report to Slack and then reroll the posts.
Instead of rerolling all posts, it should only reroll the post you reported. That way, if you see multiple rule violations you could report all of them.

Add button to app to report posts without claiming them

---

app/tests/test_views.py
app/views.py

Relevant issue: Closes #246
This handles Imgur links like https://imgur.com/OhUY1rS which don't link to the image directly.
The bot will try to slap `.jpg` at the end to properly render the image.
This does **not** fix the display of the images in the transcription choice page. Those are more annoying to handle.

Handle imgur posts that are not direct links

---

api/admin.py
api/views/slack_helpers.py
app/tests/test_views.py
app/views.py

Relevant issue: #258
Something that was brought up in Discord is that reported posts stay in the queue, and because we're not tied to Reddit anymore, we can remove these now as they come in and avoid the unfortunate situation that happened earlier with a volunteer reporting a post and then rerolling it multiple times. This PR reworks the logic of the report flow to automatically remove a post pending the response from the Slack ping, which can optionally reinstate it. Also includes some very small fixes I noticed while debugging this.

Remove submissions on report

---

api/tests/submissions/test_submission_heatmap.py
api/tests/submissions/test_submission_rate.py
api/views/submission.py

Relevant issue: Closes #301
This allows the client to specify the UTC offset in seconds, which can be used to localize the results.
I tried to do this client-side on Buttercup, but for the `rate` we don't have enough info to do it and for `heatmap` it doesn't work for time zones like `+01:30`.
So moving this functionality to the server side makes sense for us (and might be beneficial for third-party clients or our other bots).

Add `utc_offset` query parameters to `submission/rate` and `submission/heatmap` endpoints

---

api/tests/submissions/test_submission_done.py
api/tests/submissions/test_submission_transcribot_queue.py
api/views/slack_helpers.py
api/views/submission.py

Relevant issue: Closes #305
If a transcriber had a long pause and is just returning to transcribing, they should be checked again.
If they did less than 5 transcriptions in the past month, they are now guaranteed to be checked.
Otherwise, the normal system is used.
This PR also factors out some static methods out of the SubmissionViewSet and turns them into functions.

Consider recent transcriptions for check percentage

---

api/serializers.py
api/tests/submissions/test_submission_get.py
api/views/submission.py

Relevant issue: Closes #312
This PR adds the `removed_from_queue` field to the submission query parameters and the serializer so that clients can use it.

Expose `removed_from_queue` to API

---

api/tests/submissions/test_submission_remove.py
api/views/submission.py

Relevant issue: Closes #315 
This adds a new endpoint that allows us to remove (and restore) posts from the queue.
This is necessary to synchronize the Blossom and Reddit queues.

Add `submission/remove` endpoint

---

.github/workflows/tests.yml

This is an attempt to run the CI tests in parallel, via the `pytest --workers=auto` option.
This option seems to break on some systems, so we'll have to see if it actually works.
If it does, it could significantly speed up our pipeline though.

Run CI tests in parallel

---

api/views/slack_helpers.py
app/tests/test_misc.py

Saving the channel ID of a Slack report message failed, because I misunderstood the response by the Slack API.
For future reference: https://api.slack.com/methods/chat.postMessage
This also fixes submissions not being marked as removed after being reported on Reddit.

Fix saving of the Slack channel ID when reporting a post

---

api/tests/submissions/test_submission_done.py
pyproject.toml
pytest.ini

Relevant issue: https://github.com/GrafeasGroup/blossom/issues/323
Move the pytest ini information into the pyproject.toml file and also extend one test for greater coverage.

move pytest information into pyproject.toml

---

api/slack/__init__.py

This PR attempts to fix a wrong import of the Slack API which resulted in the Blossom deployment failing.
PyCharm warns with "Package containing module 'slack' is not listed in the project requirements" for the import so I'm not 100% sure if this fixes the problem.

Hotfix: Fix import of Slack API

---

api/slack/commands.py
api/tests/test_slack.py
blossom/strings/en_US.toml

This adds a Slack command to display a list of all users who are currently being watched.
Relevant issue: Closes #336
This adds a Slack command to display a list of all currently watched users.
**Usage**: `@Blossom watchlist <sorting>`, where `<sorting>` is either `percentage` (default) or `alphabetical`.
If percentage is used, the users are grouped by their overwritten watch percentage. Otherwise they are sorted alphabetically by username.

Add watchlist Slack command

---

api/slack/commands.py

The selection on which command was executed used a startswith check. When we have multiple commands that start with the same name, the wrong one might be selected.
In this PR we extract the first token instead and check for equality.

Fix command processing to check for equality

---

api/slack/commands.py

The help and ping command functions only took the channel parameter because they didn't use the message.
However, the message is still passed by the processing function, so we need to keep it in the function parameters.

Fix help and ping commands not taking enough parameters

---

api/tests/submissions/test_submission_nsfw.py
api/views/submission.py

Relevant issue: Closes #346
This endpoint allows clients to mark a submission as NSFW or set it back to SFW.
This can be used to sync up the NSFW status with the Reddit queue.

Add /submission/nsfw endpoint

---

bootstrap/__init__.py
bootstrap/sync_removal.py

This adds a bootstrap script to sync up the removal on Reddit with Blossom.
It will set the `removed_from_queue` flag for any submissions where the post has been removed for being rule breaking (on r/ToR or on the partner sub).
**Usage**:
- Specify `START_DATE` and `END_DATE` (as well as Blossom and Reddit logins) in a `.env` file in the `bootstrap` folder
- Run `python3 bootstrap/sync_removal.py`

Add script to sync removal from Reddit to Blossom

---

api/tests/submissions/test_submission_done.py
api/views/submission.py

This updates the default check percentages, as quested by the QA team:
**Old**:
```
<=   5: 100%
<=  50:  40%
<= 100:  20%
<= 250:  10%
<= 500:   5%
<=1000:   2%
<=5000:   1%
> 5000:   0.5%
```
**New**:
```
<=  10: 100%
<=  50:  50%
<= 100:  30%
<= 250:  15%
<= 500:   5%
<=1000:   2%
<=5000:   1%
> 5000:   0.5%
```

Change default check percentages as requested by QA

---

api/slack/utils.py
api/tests/submissions/test_submission_done.py
api/tests/test_slack.py
api/views/submission.py

Relevant issue: Closes #361
The OCR transcription got picked up instead of the user provided transcription.
It doesn't have a link, so `[Removed]` was displayed in the check message instead.
We now filter the transcription author to make sure that the correct one is selected.
Additionally this adds a `Γ` character to the user gamma in the check message.

Fix transcription link not being picked up correctly

---

api/slack/commands.py
api/slack/utils.py
api/tests/slack/test_commands.py
api/tests/slack/test_utils.py

Relevant issue: Closes #366
The check command now also accepts the weird Slack links.
Additionally, this improved how Slack links are recognized and extracted.

Fix link recognition for check command

---

api/slack/transcription_check/actions.py
api/slack/transcription_check/messages.py
api/slack/utils.py
api/tests/slack/transcription_check/test_actions.py

Relevant issue: Closes #370
- Get the mod username from the Slack profile instead of using the Slack username directly
- Fix `message_ts` value for `reply_to_action` function

Fix check username detection

---

api/slack/transcription_check/actions.py
api/slack/transcription_check/blocks.py
api/tests/slack/transcription_check/test_actions.py

This PR updates the check message in some error cases (such as the check being unclaimed or already being claimed).
This makes sure that the proper buttons are shown, avoiding the check being stuck in an error state.
Additionally it moves the text around a bit to make the check message more compact.

Update check on errors

---

api/slack/transcription_check/actions.py
api/tests/slack/transcription_check/test_actions.py

Relevant issue: Closes #373
This prevents a mod claiming a check for their own transcription.

Prevent a mod claiming a check for their own transcription

---

api/slack/transcription_check/blocks.py
authentication/models.py
authentication/tests/test_blossomuser.py

Relevant issue: Closes #379
This PR fixes the gamma counts displayed in the transcription checks.
Previously, it just displayed the user's current gamma, which would become inaccurate as the message gets updated.
The new version calculates the user's gamma at the point of the transcription being checked. This is consistent and more intuitive.
:warning: The gamma counts might now be off for old users :warning:
For some old users, some submissions might be missing the `complete_time` field. These transcriptions might not be counted correctly.
However, for these users the gamma count is less important and we can fix the data in the future.

Fix gamma counts in transcription checks

---

api/slack/transcription_check/actions.py
api/slack/utils.py
api/tests/slack/test_utils.py
api/tests/slack/transcription_check/test_actions.py

Relevant issue: Closes #380
We introduced a custom "Reddit Username" field for the Slack profiles so that mods can set their username there instead of having to use the Slack display name.
This field is now used to pull the username, with the display name as fallback.
Note that the Slack documentation on the "fields" attribute are very sparse, so I might have to do some debugging in production to get this fully working.

Get Reddit username through custom Slack profile field

---

api/slack/transcription_check/blocks.py
api/slack/utils.py
api/tests/slack/test_utils.py
api/tests/submissions/test_submission_done.py
api/views/submission.py
app/tests/test_views.py

Relevant issue: Closes #330
This PR migrates the automatic transcription checks to the new button-based system (used by the `check` Slack command).
It also includes some minor changes to the button workflow, removing the "Warn" button in the comment pending state and using the default style for the "Warn" button.

Migrate automatic transcription checks to the new check system

---

api/slack/transcription_check/messages.py
api/tests/slack/transcription_check/test_messages.py

Relevant issue: Closes #388
This PR adds a fallback text for transcription check messages which is displayed in notifications.

388 slack fallback text

---

api/slack/commands.py
api/slack/utils.py
api/tests/slack/test_commands.py
api/tests/slack/test_utils.py
blossom/strings/en_US.toml

Relevant issue: Closes #381
This PR improves and simplifies the username parsing for the Slack commands. All commands should now accept usernames with various formatting, including links, bold text and the u/ prefix.
Additionally, if the user could not be found, the parsed username is now included in the error message for easier debugging.

Accept bold usernames in commands

---

.github/workflows/tests.yml
.pre-commit-config.yaml
api/slack/commands/check.py
api/slack/commands/warnings.py
poetry.lock

Fixes #396 
`warnings` and `check` both automatically unfurl links (show a preview) which makes/would make scrolling back through the channel kind of chonky.
I haven't actually tested this PR out but [I followed the Slack API docs for link unfurling](https://api.slack.com/reference/messaging/link-unfurling#no_unfurling_please) and it looks like [this is what Bubbles does too for the check pings](https://github.com/GrafeasGroup/Bubbles-V2/blob/master/bubbles/commands/periodic/transcription_check_ping.py#L315) so surely I'm on the right track... right?
Deepest apologies for touching the pre-commit config... I ran into https://github.com/psf/black/issues/2964 on my local somehow and I wanted to leave my config changes unstaged, but pre-commit is too smart for that and prevented me from …

Don't preview links for check and warnings commands

---

.github/workflows/tests.yml
blossom/middleware.py
blossom/settings/base.py
blossom/settings/testing.py
blossom/strings/__init__.py
blossom/templates/website/generic_form.html
blossom/templates/website/partials/footer.partial
poetry.lock
pyproject.toml
website/forms.py
website/views.py

* update legalese in footer
* add Date field to post creator for backdating purposes
* add date widget
* remove environment from tests and revert back to just normal secret
* Bunch of flake8 changes because flake8 hates me and picks files at random just to fuck with me

Minor graphical updates and add datefield for backdating posts

---

api/slack/commands/info.py
api/tests/slack/commands/test_info.py
authentication/models.py
blossom/strings/en_US.toml
pyproject.toml

Relevant issue: Closes #404
This is a complete rework of the `info` command in Slack, providing more data and formatting it in a more readable way.
Example output:
---
Info about **[u/Userson](https://reddit.com/u/Userson)**:
**General**:
- Gamma: 5 Γ (2 Γ in last 2 weeks)
- Joined on: 2020-04-21 (1.0 year ago)
- Last active: 2021-04-13 (1.1 weeks ago)
**Transcription Quality**:
- Checks: 2 (40.0% of transcriptions)
- Warnings: 1 (50.0% of checks)
- Watch status: Automatic (100.0%)
**Debug Info**:
- ID: `123`
- Blacklisted: No
- Bot: No
- Accepted CoC: Yes

Rework the Slack `info` command

---

api/slack/commands/info.py
api/tests/slack/commands/test_info.py
pyproject.toml

Relevant issue: Closes #406
Adds the number of check comments for the user and the percentage in relation to the total checks.

Add comment count and percentage to info command

---

api/slack/transcription_check/blocks.py

Relevant issue: Closes #411
The transcription check messages now:
- Link to the Reddit profile of the user.
- Show the transcription link even if it is marked as removed.

Link to Reddit profiles in transcription check messages

---

.gitattributes
pyproject.toml

Relevant issue: Closes #415
This avoids them distorting our language stats on GitHub.

Mark vendored libraries as linguist-vendored

---

.github/workflows/static-analysis.yml

Relevant issue: https://github.com/GrafeasGroup/blossom/pull/447
The static analysis test is failing because it's an old-ass version of python. This updates the workflow to be less stuck in time.

update workflow to modern python

---

blossom/api/slack/messages/unclaim.py

This should hopefully fix the buttons of the `unclaim` command not working.

Fix unclaim actions not including the user ID

---

blossom/api/slack/actions/unclaim.py

From the logs:
```
r_tor_submission: SubmissionModeration = REDDIT.submission(submission.tor_url).mod()
TypeError: 'SubmissionModeration' object is not callable
```
The joys of dynamic typing :smiling_face_with_tear:

Fix Reddit flair update on unclaim command

---

blossom/api/slack/actions/unclaim.py

Apparently you can't do the `flair.select(...)` on a mod submission, there it has to be just `flair(...)`, because of reasons...
Sometimes I hate PRAW.

Fix wrong method call when flairing Reddit post

---

blossom/authentication/models.py
blossom/authentication/tests/test_blossomuser.py

Relevant issue: #464
It now correctly filters out None entries for claim_time and complete_time.

Fix date_last_active returning None too often

---

.flake8

Exclude the local settings file from flake8 checks as it is not committed.

Exclude local settings file from flake8

---

.github/workflows/static-analysis.yml
.pre-commit-config.yaml
.ruff.toml
blossom/api/views/find.py
blossom/api/views/submission.py
blossom/api/views/transcription.py
blossom/api/views/volunteer.py
poetry.lock
pyproject.toml

This PR replaces the linting from flake8 and isort with [ruff](https://beta.ruff.rs/docs/).
This improves the lint time from 8.74s to 0.03s on my machine.
I chose the Ruff config such that there are as little formatting changes in this PR as possible.
In the future, we probably want to re-enable some of the disabled rules and fix the corresponding errors.
I also vote to increase the maximum line length for Ruff and Black to at least 100 (and then enable the Ruff lint rule for that).
This PR also fixes the Toml entry for dev dependencies as the naming has been changed for poetry.

Switch from flake8 and isort to ruff

---

.github/pull_request_template.md

Greatly simplify the PR template to stuff we actually need.
- Screenshots: Don't really make sense for Blossom
- Testing Instructions: Pretty much always `poetry run pytest`
- Checklist: Mostly checked by CI anyways

Simplify PR template to stuff we actually need

---

blossom/api/models.py
blossom/api/views/submission.py

Relevant issue: #174 
I accidentally generated the attribute after saving. :(

:bug: fix auto saving of feed

---

blossom/api/tests/test_transcriptions.py
blossom/api/views/submission.py
blossom/api/views/transcription.py

Relevant issue: Preparation for <https://github.com/GrafeasGroup/buttercup/issues/202>.
Adds additional `submission__feed__*` filters to the transcription view.
This enables us to efficiently filter by subreddits for Buttercup commands and other functionality.

Add filters for submission feed to transcription view

---

blossom/api/slack/commands/info.py
blossom/strings/en_US.toml

Relevant issue: Closes #409
This PR reworks the `info` command when no username is provided.
It now has better formatting and includes a lot more stats.

Rework `info` command for whole project

---

blossom/api/slack/commands/checkstats.py
blossom/api/tests/slack/commands/test_checkstats.py
blossom/strings/en_US.toml

This PR extends the `checkstats` command if no mod is provided.
In this case, the stats for all mods combined are displayed.

Add check stats for all mods combined

---

blossom/authentication/models.py

For some old users, the gamma in the transcription check messages was off (by a lot).
This is probably because some old posts don't have completion times for the submissions.
The `gamma_at_time` method now also includes completed submissions without a time in the count.

Fix wrong transcription counts in check messages
